<?php /* @var $this Rootd_Installer_Update_Step2 */ ?>
<div class="update-nag step-content">
    <form action="<?php echo $this->getAction(); ?>" method="post" enctype="multipart/form-data">
        <span class="install-progress"><?php echo $this->getProgress(); ?></span>
        <h3><?php _e('Update Complete'); ?></h3>
        <p><?php _e("Rootd Framework Core has been updated successfully. Enjoy!"); ?></p>
        <p>
            <input type="submit" class="button action" value="<?php _e('OK'); ?>">
        </p>
    </form>
</div>